# TODO: take in fellow first name
fname = ...

# TODO: take in fellow track name
track = ...

# TODO: take in the names of fellows that they know
name = ...
familiars = []
while name != "exit":
    familiars.append(name)
    name = ...

# TODO: print out all information
...
